using Microsoft.Data.SqlClient;
using System.Data;

namespace DisconnectedDemo01
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string connstr = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=yuvraj;Integrated Security=True;";
            #region GetData
            //SqlConnection conn = new SqlConnection(connstr);
            //conn.Open();
            //SqlDataAdapter adapter = new SqlDataAdapter("select * from emp",conn);
            //adapter.MissingSchemaAction=MissingSchemaAction.AddWithKey;
            //DataSet ds = new DataSet();
            //adapter.Fill(ds, "Emp");

            //foreach (DataRow item in ds.Tables["Emp"].Rows)
            //{
            //    int id=Convert.ToInt32(item["ID"]);
            //    string nm=item["EmpName"].ToString();
            //    string addr=item["EmpAddress"].ToString();
            //    Console.WriteLine($"Id: {id}, Name: {nm}, Address: {addr}");
            //} 
            #endregion

            #region INSERT Query
            SqlConnection con = new SqlConnection(_ConStr);
            SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMP", con);

            da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            SqlCommandBuilder builder = new SqlCommandBuilder(da);

            DataSet ds = new DataSet();
            da.Fill(ds, "Emp");
            //ds.GetXml()

            Console.WriteLine("Enter Name:");
            string nm = Console.ReadLine();
            Console.WriteLine("Enter Address:");
            string add = Console.ReadLine();

            DataRow newRow = ds.Tables["Emp"].NewRow();
            newRow["Name"] = nm;
            newRow["Address"] = add;

            ds.Tables["Emp"].Rows.Add(newRow);

            da.Update(ds, "Emp");//Insert Query is generated by CommandBuilder
            Console.WriteLine("Record inserted!");


            #endregion
        }
    }
}
